# Generated by Django 5.2.3 on 2025-06-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexao',
            name='port_local',
            field=models.CharField(default=3050, max_length=50),
            preserve_default=False,
        ),
    ]
