# Generated by Django 5.2.3 on 2025-06-20 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0002_conexao_port_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteSeguranca',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente (Segurança)',
                'verbose_name_plural': '🔒 Segurança por Cliente',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cliente_app.cliente',),
        ),
        migrations.AlterField(
            model_name='conexao',
            name='port_local',
            field=models.CharField(default='3050', max_length=50),
        ),
        migrations.CreateModel(
            name='SecGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_groups', to='cliente_app.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'group_id')},
            },
        ),
        migrations.CreateModel(
            name='SecGroupApp',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('cod_modulo', models.CharField(max_length=50)),
                ('cod_projeto', models.CharField(max_length=50)),
                ('app_name', models.CharField(max_length=100)),
                ('priv_access', models.BooleanField(default=False)),
                ('priv_insert', models.BooleanField(default=False)),
                ('priv_update', models.BooleanField(default=False)),
                ('priv_export', models.BooleanField(default=False)),
                ('priv_print', models.BooleanField(default=False)),
                ('priv_jaentrego', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_group_apps', to='cliente_app.cliente')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='cliente_app.secgroup')),
            ],
        ),
        migrations.CreateModel(
            name='SecUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('pswd', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('activation_code', models.CharField(blank=True, max_length=100, null=True)),
                ('priv_admin', models.BooleanField(default=False)),
                ('mfa', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('role', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('pswd_last_updated', models.DateTimeField(auto_now=True)),
                ('mfa_last_updated', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_users', to='cliente_app.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'login')},
            },
        ),
        migrations.CreateModel(
            name='SecSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=50)),
                ('set_value', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_settings', to='cliente_app.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'set_name')},
            },
        ),
        migrations.CreateModel(
            name='SecUsersGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_users_groups', to='cliente_app.cliente')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='cliente_app.secgroup')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='cliente_app.secuser')),
            ],
            options={
                'unique_together': {('cliente', 'login', 'group')},
            },
        ),
    ]
