# Generated by Django 5.2.3 on 2025-06-26 20:39

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0005_cria_projetoaplicacaodetalhe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoAplicacaoSubprojeto',
            fields=[
                ('cod_seq', models.AutoField(primary_key=True, serialize=False)),
                ('nome_aplicacao', models.CharField(max_length=100)),
                ('nome_demonstracao', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('cod_relacao', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='subprojetos',
                    to='cliente_app.projetoaplicacao'
                )),
            ],
        ),
    ]
