# Generated by Django 5.2.3 on 2025-06-27 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0006_remove_projetoaplicacaodetalhe_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetoaplicacaodetalhe',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='projetoaplicacaodetalhe',
            name='projeto',
        ),
        migrations.CreateModel(
            name='AplicacaoSubprojeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aplicacao', models.CharField(max_length=100)),
                ('subprojeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='cliente_app.projetoaplicacaosubprojeto')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteProjetoAplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_vinculados', to='cliente_app.cliente')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_vinculados', to='cliente_app.projetoaplicacao')),
            ],
            options={
                'unique_together': {('cliente', 'projeto')},
            },
        ),
        migrations.AddField(
            model_name='projetoaplicacaodetalhe',
            name='cliente_projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='cliente_app.clienteprojetoaplicacao'),
            preserve_default=False,
        ),
    ]
