# Generated by Django 5.2.3 on 2025-07-02 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0007_remove_projetoaplicacaodetalhe_cliente_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clienteprojetoaplicacao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clienteprojetoaplicacao',
            name='subprojeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_vinculados', to='cliente_app.projetoaplicacaosubprojeto'),
        ),
        migrations.AlterUniqueTogether(
            name='clienteprojetoaplicacao',
            unique_together={('cliente', 'projeto', 'subprojeto')},
        ),
    ]
