# Generated by Django 5.2.3 on 2025-08-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0008_alter_clienteprojetoaplicacao_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
