"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os  # <== não esqueça disso no topo do arquivo!
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!*5o)i62!+*2a_d&%nzlq$@-(x-n=1$+r3s-ln@4j=e8j9@c!f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'cliente_app.apps.ClienteAppConfig',
]

JAZZMIN_SETTINGS = {
    "site_title": "Painel Admin",
    "site_header": "Administração",
    "custom_css": "css/darkmode.css",

    "custom_menu": [
        {
            "name": "Dashboard",
            "url": "/admin/dashboard/",
            "icon": "fas fa-tachometer-alt",
            "permissions": [],  # sem restrição de permissão
        },
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # Pode ficar vazio porque APP_DIRS=True busca dentro dos apps
        'APP_DIRS': True,  # Importante para buscar templates dentro de cada app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # Necessário para algumas features do admin
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.sqlite3',
   #     'NAME': BASE_DIR / 'db.sqlite3',
    #}
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bd_sup',
        'USER': 'postgres',
        'PASSWORD': 'senha4253',
        'HOST': 'db',  # EX: 'postgres-bd', 'db', etc
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

JAZZMIN_SETTINGS = {
    "site_title": "Painel Admin",
    "site_header": "Administração",
    "custom_css": "css/darkmode.css",

    "custom_meu": [
        {
            "name": "Dashboard",
            "url":  "/dashboard/",
            "icon": "fas fa-tachometer-alt",
        },
        #Se quiser adicionar mais itens, é só colocar aqui
    ],
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static", # para garantir que /static/css seja encontrado
]

STATIC_ROOT = BASE_DIR / "staticfiles"  # onde o collectstatic joga os arquivos

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'